apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-demo-sa
  namespace: secrets-demo
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/myapp-dev-app-role"
    eks.amazonaws.com/token-expiration-seconds: "3600"
